# cog.toml

# Configuration for cocogitto. cocogitto is a tool for managing conventional
# commits, version bumps etc..

# This is needed for semantic versioning.
tag_prefix = "v"

pre_bump_hooks = [
    "echo {{version}}",
    "git checkout -b release-v{{version}}"
]

post_bump_hooks = [
    # Delete the version because we have to create a PR first.
    "git tag -d v{{version}}"
]

[commit_types]
feat = { changelog_title = "Features" }
fix = { changelog_title = "Bug Fixes" }
docs = { changelog_title = "", omit_from_changelog = true }
chore = { changelog_title = "", omit_from_changelog = true }
refactor = { changelog_title = "", omit_from_changelog = true }
style = { changelog_title = "", omit_from_changelog = true }
build = { changelog_title = "", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "Performance Improvements" }
revert = { changelog_title = "", omit_from_changelog = true }
test = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "runeio"
owner = "ianlewis"
authors = [
  { username = "ianlewis", signature = "Ian Lewis"}
]
